// frontend_uniapp/src/pages/my-published/my-published.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { useUserStore } from '@/store/user'
import { getMyCircles, deleteCircle } from '@/api/circles'
import type { CircleDTO } from '@/types'

definePage({
  style: {
    navigationBarTitleText: '我发布的圈子',
  },
})

/** 圈子状态展示配置 */
const STATUS_CONFIG: Record<string, { text: string; cls: string }> = {
  active: { text: '正常', cls: 'bg-[#e8f5f1] text-[#018d71]' },
  offline: { text: '已下线', cls: 'bg-[#eef0f2] text-[#666]' },
  violated: { text: '违规', cls: 'bg-[#fff1f0] text-[#ff4d4f]' },
}

const userStore = useUserStore()

const list = ref<CircleDTO[]>([])
const loading = ref(false)
const deletingId = ref<string | null>(null)

/** 拉取我创建的圈子(排除 deleted) */
async function fetchList() {
  loading.value = true
  try {
    const res = await getMyCircles({ page: 1, pageSize: 20 })
    // 后端已过滤 deleted,这里再兜底过滤一遍
    const filtered = (res.list || []).filter(c => c.status !== 'deleted')
    list.value = filtered
  }
  catch (e) {
    uni.showToast({ title: (e as Error).message || '加载失败', icon: 'none' })
  }
  finally {
    loading.value = false
  }
}

// 进入时权限校验 + 拉取
onShow(() => {
  const role = userStore.userInfo?.role
  if (role !== 'TEACHER') {
    uni.showToast({ title: '仅传承人可访问', icon: 'none' })
    setTimeout(() => uni.navigateBack(), 800)
    return
  }
  void fetchList()
})

/** 下拉刷新 */
onPullDownRefresh(() => {
  fetchList().finally(() => {
    uni.stopPullDownRefresh()
  })
})

/** 跳编辑页 */
function handleEdit(id: string) {
  uni.navigateTo({ url: `/pages/create-circle/create-circle?id=${id}` })
}

/** 下线圈子:showModal 确认后调 deleteCircle 软删除 */
function handleOffline(id: string, title: string) {
  if (deletingId.value) return
  uni.showModal({
    title: '下线圈子',
    content: `确定下线「${title}」吗?下线后不再被匹配。`,
    confirmText: '下线',
    cancelText: '取消',
    confirmColor: '#f53f3f',
    success(res) {
      if (!res.confirm) return
      deletingId.value = id
      deleteCircle(id)
        .then(() => {
          // 从列表移除(后端软删除,前端不再展示)
          list.value = list.value.filter(c => c.id !== id)
          uni.showToast({ title: '已下线', icon: 'success' })
        })
        .catch((e) => {
          uni.showToast({ title: (e as Error).message || '下线失败', icon: 'none' })
        })
        .finally(() => {
          deletingId.value = null
        })
    },
  })
}

/** 创建时间格式化(只到日) */
function formatDate(iso: string | null): string {
  if (!iso) return ''
  try {
    const d = new Date(iso)
    if (Number.isNaN(d.getTime())) return ''
    const pad = (n: number) => String(n).padStart(2, '0')
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
  }
  catch {
    return ''
  }
}

/** 渲染状态 chip */
function statusCls(status: string): string {
  const cfg = STATUS_CONFIG[status]
  return cfg ? cfg.cls : 'bg-[#eef0f2] text-[#666]'
}
function statusText(status: string): string {
  const cfg = STATUS_CONFIG[status]
  return cfg ? cfg.text : status
}
</script>

<template>
  <view class="flex min-h-screen flex-col bg-[#f7f8fa]">
    <view class="bg-white px-4 py-4">
      <text class="block text-base font-semibold text-[#333]">
        我发布的圈子
      </text>
      <text class="mt-1 block text-xs text-[#999]">
        仅传承人可见;共 {{ list.length }} 个
      </text>
    </view>

    <view v-if="loading && list.length === 0" class="flex flex-col items-center pt-20">
      <text class="text-sm text-[#999]">
        加载中...
      </text>
    </view>
    <view v-else-if="list.length === 0" class="flex flex-col items-center pt-20">
      <text class="text-sm text-[#999]">
        你还没有发布过圈子,去创建一个吧
      </text>
    </view>
    <view v-else class="mx-4 mt-3 flex flex-col gap-3">
      <view v-for="c in list" :key="c.id" class="rounded-2xl bg-white p-4">
        <view class="flex items-start justify-between gap-2">
          <view class="min-w-0 flex-1">
            <view class="flex items-center gap-2">
              <text class="truncate text-base font-medium text-[#333]">
                {{ c.title }}
              </text>
              <text class="shrink-0 rounded-full px-2 py-0.5 text-xs" :class="statusCls(c.status)">
                {{ statusText(c.status) }}
              </text>
            </view>
            <view class="mt-1 flex items-center gap-1">
              <text class="text-xs text-[#999]">
                {{ c.memberCount }}/{{ c.maxMembers ?? '不限' }}人
              </text>
              <text class="text-xs text-[#999]">
                ·
              </text>
              <text class="text-xs text-[#999]">
                创建于 {{ formatDate(c.createdAt) }}
              </text>
            </view>
            <text v-if="c.activityTime" class="mt-1 block text-xs text-[#999]">
              活动时间:{{ c.activityTime }}
            </text>
          </view>
        </view>
        <view class="mt-3 flex gap-3">
          <view class="rounded-full border border-[#e0e0e0] px-4 py-1.5" @click="handleEdit(c.id)">
            <text class="text-sm text-[#666]">
              编辑
            </text>
          </view>
          <view
            class="rounded-full border border-[#ffd6d6] px-4 py-1.5"
            :class="deletingId === c.id ? 'opacity-60' : ''"
            @click="deletingId === c.id ? null : handleOffline(c.id, c.title)"
          >
            <text class="text-sm text-[#ff4d4f]">
              {{ deletingId === c.id ? '下线中...' : '下线' }}
            </text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<style lang="scss" scoped>
//
</style>

// frontend/src/pages/my-published/index.tsx
import React, { useCallback, useState } from 'react';
import { View, Text, ScrollView } from '@tarojs/components';
import { Tag, Button } from '@nutui/nutui-react-taro';
import Taro, { useDidShow } from '@tarojs/taro';
import { getMyCircles, deleteCircle } from '@/services/circles';
import { useUserStore } from '@/store/user';
import styles from './index.module.scss';

/** 圈子状态展示配置 */
const STATUS_CONFIG: Record<
  string,
  { text: string; type: 'success' | 'primary' | 'danger' }
> = {
  active: { text: '正常', type: 'success' },
  offline: { text: '已下线', type: 'primary' },
  violated: { text: '违规', type: 'danger' },
};

/** 创建时间格式化(只到日) */
function formatDate(iso: string | null): string {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return '';
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  } catch {
    return '';
  }
}

/**
 * 我发布的圈子页(TEACHER 专属)。
 *
 * - 进入时调 getMyCircles 拉取当前用户创建的圈子列表
 * - 列表项:标题 + 状态 chip + 成员数 + 创建时间
 *   (CircleDTO 不含 tags,故不展示标签;若后端后续扩展可补充)
 * - 操作:编辑(跳 create-circle?id=xxx)/ 下线(showModal 确认后 deleteCircle)
 * - 下拉刷新
 * - 非 TEACHER 访问:Toast + navigateBack
 */
const MyPublishedPage: React.FC = () => {
  const [list, setList] = useState<CircleDTO[]>([]);
  const [loading, setLoading] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  /** 拉取我创建的圈子(排除 deleted) */
  const fetchList = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getMyCircles({ page: 1, pageSize: 20 });
      // 后端已过滤 deleted,这里再兜底过滤一遍
      const filtered = (res.list || []).filter(
        (c) => c.status !== 'deleted'
      );
      setList(filtered);
    } catch (e) {
      Taro.showToast({
        title: (e as Error).message || '加载失败',
        icon: 'none',
      });
    } finally {
      setLoading(false);
    }
  }, []);

  // 进入时权限校验 + 拉取
  useDidShow(() => {
    const role = useUserStore.getState().user?.role;
    if (role !== 'TEACHER') {
      Taro.showToast({ title: '仅传承人可访问', icon: 'none' });
      setTimeout(() => Taro.navigateBack(), 800);
      return;
    }
    void fetchList();
  });

  /** 下拉刷新 */
  Taro.usePullDownRefresh(() => {
    fetchList().finally(() => {
      Taro.stopPullDownRefresh();
    });
  });

  /** 跳编辑页 */
  const handleEdit = (id: string): void => {
    Taro.navigateTo({ url: `/pages/create-circle/index?id=${id}` });
  };

  /** 下线圈子:showModal 确认后调 deleteCircle 软删除 */
  const handleOffline = (id: string, title: string): void => {
    if (deletingId) return;
    Taro.showModal({
      title: '下线圈子',
      content: `确定下线「${title}」吗?下线后不再被匹配。`,
      confirmText: '下线',
      cancelText: '取消',
      confirmColor: '#f53f3f',
    })
      .then(async (res) => {
        if (!res.confirm) return;
        setDeletingId(id);
        try {
          await deleteCircle(id);
          // 从列表移除(后端软删除,前端不再展示)
          setList((prev) => prev.filter((c) => c.id !== id));
          Taro.showToast({ title: '已下线', icon: 'success' });
        } catch (e) {
          Taro.showToast({
            title: (e as Error).message || '下线失败',
            icon: 'none',
          });
        } finally {
          setDeletingId(null);
        }
      })
      .catch(() => {
        // 取消,静默
      });
  };

  // 渲染状态 chip(若状态未知默认为 primary)
  const renderStatus = (status: string): React.ReactElement => {
    const cfg = STATUS_CONFIG[status] || { text: status, type: 'primary' as const };
    return (
      <Tag type={cfg.type} className={styles.statusChip}>
        {cfg.text}
      </Tag>
    );
  };

  return (
    <View className={styles.page}>
      <View className={styles.header}>
        <Text className={styles.headerTitle}>我发布的圈子</Text>
        <Text className={styles.headerHint}>
          仅传承人可见;共 {list.length} 个
        </Text>
      </View>

      {loading && list.length === 0 ? (
        <View className={styles.empty}>
          <Text className={styles.emptyText}>加载中...</Text>
        </View>
      ) : list.length === 0 ? (
        <View className={styles.empty}>
          <Text className={styles.emptyText}>
            你还没有发布过圈子,去创建一个吧
          </Text>
        </View>
      ) : (
        <ScrollView scrollY className={styles.list}>
          {list.map((c) => {
            return (
              <View key={c.id} className={styles.card}>
                <View className={styles.cardHead}>
                  <View className={styles.cardMain}>
                    <View className={styles.titleRow}>
                      <Text className={styles.title}>{c.title}</Text>
                      {renderStatus(c.status)}
                    </View>
                    <View className={styles.metaRow}>
                      <Text className={styles.meta}>
                        {c.memberCount}/{c.maxMembers ?? '不限'}人
                      </Text>
                      <Text className={styles.dot}>·</Text>
                      <Text className={styles.meta}>
                        创建于 {formatDate(c.createdAt)}
                      </Text>
                    </View>
                    {c.activityTime && (
                      <Text className={styles.meta}>
                        活动时间:{c.activityTime}
                      </Text>
                    )}
                  </View>
                </View>

                <View className={styles.actions}>
                  <Button
                    type="default"
                    size="small"
                    shape="round"
                    onClick={() => handleEdit(c.id)}
                    className={styles.actionBtn}
                  >
                    编辑
                  </Button>
                  <Button
                    type="danger"
                    size="small"
                    shape="round"
                    loading={deletingId === c.id}
                    onClick={() => handleOffline(c.id, c.title)}
                    className={styles.actionBtn}
                  >
                    下线
                  </Button>
                </View>
              </View>
            );
          })}
        </ScrollView>
      )}
    </View>
  );
};

export default MyPublishedPage;
