// frontend_uniapp/src/pages/create-circle/create-circle.vue
<script lang="ts" setup>
import { computed, ref } from 'vue'
import { useUserStore } from '@/store/user'
import { createCircle, getCircle, updateCircle } from '@/api/circles'
import { uploadFile } from '@/api/upload'
import { LOGIN_PAGE } from '@/router/config'
import type { CircleDetailDTO, TagDTO, UpdateCircleInput } from '@/types'

definePage({
  style: {
    navigationBarTitleText: '创建圈子',
  },
})

/** 标题最大长度 */
const TITLE_MAX = 50
/** 描述最大长度 */
const DESCRIPTION_MAX = 500
/** 标签最大数量 */
const TAGS_MAX = 5
/** 人数上限范围 */
const MAX_MEMBERS_MIN = 1
const MAX_MEMBERS_MAX = 999
/** 手机号校验(11 位) */
const PHONE_RE = /^1\d{10}$/
/** 轮播图片最大数量 */
const COVER_IMAGES_MAX = 9

const userStore = useUserStore()

// 路由参数
const editId = ref<string>('')
const isEdit = computed(() => !!editId.value)
const loading = ref(false)

// 表单状态
const title = ref('')
const tagIds = ref<string[]>([])
const selectedTags = ref<TagDTO[] | undefined>(undefined)
const description = ref('')
const address = ref('')
const latitude = ref<number | null>(null)
const longitude = ref<number | null>(null)
const contactPhone = ref('')
const wechat = ref('')
const activityTime = ref('')
const maxMembers = ref('')
const submitting = ref(false)
const pickerVisible = ref(false)
const coverImages = ref<string[]>([])
const uploadingCover = ref(false)
const tagSelectorOpen = ref(false)

let hasFetched = false

/** 拉取圈子详情用于编辑预填 */
async function fetchForEdit(id: string) {
  loading.value = true
  try {
    const data: CircleDetailDTO = await getCircle(id)
    title.value = data.title || ''
    tagIds.value = data.tags.map(t => t.id)
    selectedTags.value = data.tags
    description.value = data.description || ''
    address.value = data.address || ''
    latitude.value = data.latitude
    longitude.value = data.longitude
    contactPhone.value = data.contactPhone || ''
    wechat.value =data.wechat || ''
    activityTime.value = data.activityTime || ''
    maxMembers.value = data.maxMembers != null ? String(data.maxMembers) : ''
    coverImages.value = data.coverImages || []
  }
  catch (e) {
    uni.showToast({ title: (e as Error).message || '加载失败', icon: 'none' })
  }
  finally {
    loading.value = false
  }
}

onShow(() => {
  if (!userStore.isLoggedIn) {
    uni.reLaunch({ url: LOGIN_PAGE })
    return
  }
  // 取路由参数
  const pages = getCurrentPages()
  const current = pages[pages.length - 1] as any
  editId.value = current?.options?.id || current?.$page?.options?.id || ''
  // 新建模式:仅 TEACHER / ADMIN 可创建圈子,其余角色先完成教师认证
  if (!isEdit.value && !['TEACHER', 'ADMIN'].includes(userStore.userInfo?.role ?? '')) {
    uni.showToast({ title: '请先完成教师认证', icon: 'none' })
    uni.navigateTo({ url: '/pages/teacher-certification/teacher-certification' })
    return
  }
  if (isEdit.value && !hasFetched) {
    hasFetched = true
    void fetchForEdit(editId.value)
  }
})

// 表单校验
const trimmedTitle = computed(() => title.value.trim())
const titleValid = computed(() => trimmedTitle.value.length >= 1 && trimmedTitle.value.length <= TITLE_MAX)
const tagsValid = computed(() => tagIds.value.length >= 1 && tagIds.value.length <= TAGS_MAX)
const locationValid = computed(() => !!address.value && latitude.value !== null && longitude.value !== null)
const descriptionValid = computed(() => description.value.trim().length >= 1 && description.value.trim().length <= DESCRIPTION_MAX)
const hasContact = computed(() => contactPhone.value.trim() !== '' || wechat.value.trim() !== '')
const phoneValid = computed(() => contactPhone.value.trim() === '' || PHONE_RE.test(contactPhone.value.trim()))
const maxMembersNum = computed(() => (maxMembers.value === '' ? null : Number(maxMembers.value)))
const maxMembersValid = computed(() =>
  maxMembers.value === ''
  || (!Number.isNaN(maxMembersNum.value as number)
    && (maxMembersNum.value as number) >= MAX_MEMBERS_MIN
    && (maxMembersNum.value as number) <= MAX_MEMBERS_MAX))
const canSubmit = computed(() =>
  titleValid.value && descriptionValid.value && tagsValid.value && locationValid.value
  && hasContact.value && phoneValid.value && maxMembersValid.value && !submitting.value)

const formErr = computed((): string => {
  if (!hasContact.value) return '请至少填写一种联系方式'
  if (!phoneValid.value) return '手机号格式不正确(11 位)'
  if (!maxMembersValid.value) return `人数上限范围 ${MAX_MEMBERS_MIN}-${MAX_MEMBERS_MAX}`
  return ''
})

// 选择地点
async function handleChooseLocation() {
  // #ifdef H5
  pickerVisible.value = true
  return
  // #endif
  // #ifndef H5
  try {
    const res = await uni.chooseLocation({})
    latitude.value = res.latitude
    longitude.value = res.longitude
    address.value = res.address || res.name || '已选择位置'
  }
  catch (e) {
    const err = e as Error & { errMsg?: string }
    if (err?.errMsg && /cancel/i.test(err.errMsg)) return
    uni.showToast({ title: err?.message || '定位失败', icon: 'none' })
  }
  // #endif
}

function handlePickerConfirm(loc: { latitude: number; longitude: number; address: string }) {
  latitude.value = loc.latitude
  longitude.value = loc.longitude
  address.value = loc.address
  pickerVisible.value = false
}

// 上传轮播图片
async function handlePickCover() {
  if (uploadingCover.value) return
  const remaining = COVER_IMAGES_MAX - coverImages.value.length
  if (remaining <= 0) {
    uni.showToast({ title: `最多 ${COVER_IMAGES_MAX} 张`, icon: 'none' })
    return
  }
  try {
    const res = await uni.chooseMedia({
      count: remaining,
      mediaType: ['image'],
      sourceType: ['album', 'camera'],
      sizeType: ['compressed'],
      maxDuration: 60,
      camera: 'back',
    })
    if (!(res as any)?.tempFiles?.length) return
    uploadingCover.value = true
    const uploaded: string[] = []
    for (const f of (res as any).tempFiles) {
      try {
        const file: string | File = f.originalFileObj ?? f.tempFilePath
        const name = (f.originalFileObj && f.originalFileObj.name)
          || f.tempFilePath
          || `cover-${Date.now()}`
        const result = await uploadFile({ file, name, purpose: 'generic' })
        uploaded.push(result.url)
      }
      catch (e) {
        console.warn('[create-circle] cover upload failed:', e)
      }
    }
    if (uploaded.length === 0) {
      uni.showToast({ title: '上传失败', icon: 'none' })
      return
    }
    coverImages.value = [...coverImages.value, ...uploaded].slice(0, COVER_IMAGES_MAX)
    uni.showToast({ title: `已上传 ${uploaded.length} 张`, icon: 'success' })
  }
  catch (e) {
    const err = e as Error & { errMsg?: string }
    if (err?.errMsg && /cancel/i.test(err.errMsg)) return
    uni.showToast({ title: err?.message || '选择失败', icon: 'none' })
  }
  finally {
    uploadingCover.value = false
  }
}

function handleRemoveCover(idx: number) {
  coverImages.value = coverImages.value.filter((_, i) => i !== idx)
}

// 提交
async function handleSubmit() {
  if (!canSubmit.value) return
  submitting.value = true
  try {
    const lat = latitude.value as number
    const lng = longitude.value as number
    const finalMax = maxMembers.value === '' ? undefined : Number(maxMembers.value)

    if (isEdit.value) {
      const patch: UpdateCircleInput = {
        title: trimmedTitle.value,
        tagIds: tagIds.value,
        description: description.value.trim(),
        contactPhone: contactPhone.value.trim() || undefined,
        wechat: wechat.value.trim() || undefined,
        activityTime: activityTime.value.trim() || undefined,
        maxMembers: finalMax,
        coverImages: coverImages.value,
      }
      await updateCircle(editId.value, patch)
      uni.redirectTo({ url: `/pages/circle/circle?id=${editId.value}` })
    }
    else {
      const res = await createCircle({
        title: trimmedTitle.value,
        tagIds: tagIds.value,
        description: description.value.trim(),
        latitude: lat,
        longitude: lng,
        address: address.value || '已定位',
        contactPhone: contactPhone.value.trim() || undefined,
        wechat: wechat.value.trim() || undefined,
        activityTime: activityTime.value.trim() || undefined,
        maxMembers: finalMax,
        coverImages: coverImages.value,
      })
      uni.redirectTo({ url: `/pages/circle/circle?id=${res.circleId}` })
    }
  }
  catch (e) {
    uni.showToast({ title: (e as Error).message || '提交失败', icon: 'none' })
  }
  finally {
    submitting.value = false
  }
}

const titleCount = computed(() => `${title.value.length}/${TITLE_MAX}`)
const descCount = computed(() => `${description.value.length}/${DESCRIPTION_MAX}`)
const tagsCountText = computed(() => `${tagIds.value.length}/${TAGS_MAX}`)
</script>

<template>
  <view class="flex min-h-screen flex-col bg-[#f7f8fa] pb-40">
    <view v-if="loading && isEdit" class="flex flex-col items-center pt-32">
      <text class="text-sm text-[#999]">
        加载中...
      </text>
    </view>

    <template v-else>
      <scroll-view scroll-y class="flex-1">
        <!-- 1. 标题 -->
        <view class="mx-4 mt-4 rounded-2xl bg-white p-4">
          <view class="flex items-center justify-between">
            <text class="text-sm font-medium text-[#333]">
              标题 <text class="text-[#f53f3f]">*</text>
            </text>
            <text class="text-xs text-[#999]">{{ titleCount }}</text>
          </view>
          <input
            v-model="title"
            class="mt-2 h-10 w-full rounded-lg bg-[#f5f6f7] px-3 text-sm"
            :maxlength="TITLE_MAX"
            placeholder="1-50 字符,如:陈氏太极拳晨练班"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 2. 兴趣标签 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <view class="flex items-center justify-between">
            <text class="text-sm font-medium text-[#333]">
              兴趣标签 <text class="text-[#f53f3f]">*</text>
            </text>
            <text class="text-xs text-[#999]">{{ tagsCountText }}</text>
          </view>
          <view class="mt-2">
            <TagSelector
              :selected-ids="tagIds"
              :max="TAGS_MAX"
              :selected-tags="selectedTags"
              @update:selected-ids="tagIds = $event"
            />
          </view>
        </view>

        <!-- 3. 描述 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <view class="flex items-center justify-between">
            <text class="text-sm font-medium text-[#333]">
              圈子介绍 <text class="text-[#f53f3f]">*</text>
            </text>
            <text class="text-xs text-[#999]">{{ descCount }}</text>
          </view>
          <textarea
            v-model="description"
            class="mt-2 h-32 w-full rounded-lg bg-[#f5f6f7] p-3 text-sm leading-6"
            :maxlength="DESCRIPTION_MAX"
            placeholder="1-500 字符,介绍圈子内容、目标人群等"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 3.5 轮播图片 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <view class="flex items-center justify-between">
            <text class="text-sm font-medium text-[#333]">轮播图片</text>
            <text class="text-xs text-[#999]">{{ coverImages.length }}/{{ COVER_IMAGES_MAX }}</text>
          </view>
          <text class="mt-1 block text-xs text-[#999]">
            可上传 0-9 张图片,首张为默认封面
          </text>
          <view class="mt-3 flex flex-wrap gap-2">
            <view
              v-for="(url, idx) in coverImages"
              :key="`${url}-${idx}`"
              class="relative h-20 w-20 overflow-hidden rounded-lg"
            >
              <image :src="url" class="h-full w-full" mode="aspectFill" />
              <view v-if="idx === 0" class="absolute left-0 top-0 rounded-br-lg bg-[#018d71] px-1.5 py-0.5">
                <text class="text-[10px] text-white">封面</text>
              </view>
              <view
                class="absolute right-0 top-0 flex h-5 w-5 items-center justify-center rounded-bl-lg bg-black/50"
                @click="handleRemoveCover(idx)"
              >
                <text class="text-xs text-white">×</text>
              </view>
            </view>
            <view
              v-if="coverImages.length < COVER_IMAGES_MAX"
              class="flex h-20 w-20 flex-col items-center justify-center rounded-lg border border-dashed border-[#e0e0e0] bg-[#fafafa]"
              @click="handlePickCover"
            >
              <text class="text-2xl text-[#ccc]">+</text>
              <text class="mt-0.5 text-xs text-[#999]">{{ uploadingCover ? '上传中' : '添加' }}</text>
            </view>
          </view>
        </view>

        <!-- 4. 活动地点 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <text class="text-sm font-medium text-[#333]">
            活动地点 <text class="text-[#f53f3f]">*</text>
          </text>
          <view class="mt-2 flex items-center justify-between rounded-lg bg-[#f5f6f7] p-3" @click="handleChooseLocation">
            <text :class="address ? 'text-sm text-[#333]' : 'text-sm text-[#bbb]'">
              {{ address || '点击选择活动地点' }}
            </text>
            <text class="text-sm text-[#018d71]">选择 ›</text>
          </view>
        </view>

        <!-- 5. 联系电话 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <text class="text-sm font-medium text-[#333]">联系电话</text>
          <input
            v-model="contactPhone"
            class="mt-2 h-10 w-full rounded-lg bg-[#f5f6f7] px-3 text-sm"
            type="number"
            :maxlength="11"
            placeholder="11 位手机号(与微信号至少填一个)"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 6. 微信号 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <text class="text-sm font-medium text-[#333]">微信号</text>
          <input
            v-model="wechat"
            class="mt-2 h-10 w-full rounded-lg bg-[#f5f6f7] px-3 text-sm"
            placeholder="微信号(与联系电话至少填一个)"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 7. 活动时间 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <text class="text-sm font-medium text-[#333]">活动时间</text>
          <input
            v-model="activityTime"
            class="mt-2 h-10 w-full rounded-lg bg-[#f5f6f7] px-3 text-sm"
            placeholder="如:每周六上午 9:00-11:00"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 8. 人数上限 -->
        <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
          <text class="text-sm font-medium text-[#333]">人数上限</text>
          <input
            v-model="maxMembers"
            class="mt-2 h-10 w-full rounded-lg bg-[#f5f6f7] px-3 text-sm"
            type="number"
            :placeholder="`可选,范围 ${MAX_MEMBERS_MIN}-${MAX_MEMBERS_MAX}`"
            placeholder-class="text-[#bbb]"
          />
        </view>

        <!-- 审核提示 -->
        <text v-if="!isEdit" class="mx-4 mt-3 block text-xs text-[#999]">
          提交后需管理员审核通过,圈子才能上线
        </text>
      </scroll-view>

      <!-- 底部提交按钮 -->
      <view class="border-t border-[#f0f0f0] bg-white px-4 py-3 pb-safe">
        <wd-button
          block
          :loading="submitting"
          :disabled="!canSubmit"
          @click="handleSubmit"
        >
          {{ isEdit ? '保存修改' : '创建圈子' }}
        </wd-button>
        <text v-if="formErr" class="mt-2 block text-center text-xs text-[#f53f3f]">
          {{ formErr }}
        </text>
      </view>

      <!-- H5 地图选点 -->
      <!-- #ifdef H5 -->
      <H5LocationPicker
        :visible="pickerVisible"
        :initial-lat="latitude"
        :initial-lng="longitude"
        @confirm="handlePickerConfirm"
        @close="pickerVisible = false"
      />
      <!-- #endif -->
    </template>
  </view>
</template>

<style lang="scss" scoped>
//
</style>

// frontend/src/pages/create-circle/index.tsx
import React, { useMemo, useRef, useState } from 'react';
import { View, Text, ScrollView, Image } from '@tarojs/components';
import { Input, TextArea, Button } from '@nutui/nutui-react-taro';
import Taro, { useDidShow, useRouter } from '@tarojs/taro';
import TagSelector from '@/components/TagSelector';
import H5LocationPicker from '@/components/H5LocationPicker';
import {
  createCircle,
  getCircle,
  updateCircle,
} from '@/services/circles';
import { uploadFile } from '@/services/upload';
import { useUserStore } from '@/store/user';
import styles from './index.module.scss';

/** 标题最大长度 */
const TITLE_MAX = 50;
/** 描述最大长度 */
const DESCRIPTION_MAX = 500;
/** 标签最大数量 */
const TAGS_MAX = 5;
/** 人数上限范围 */
const MAX_MEMBERS_MIN = 1;
const MAX_MEMBERS_MAX = 999;
/** 手机号校验(11 位) */
const PHONE_RE = /^1\d{10}$/;
/** 轮播图片最大数量 */
const COVER_IMAGES_MAX = 9;

/**
 * 创建/编辑圈子页。
 *
 * 路由:
 * - `/pages/create-circle/index` 新建模式(仅 TEACHER 可访问)
 * - `/pages/create-circle/index?id=xxx` 编辑模式:进入时调 getCircle 预填表单
 *
 * 提交流程:
 * 1. 新建模式调 createCircle,编辑模式调 updateCircle
 *    注意:UpdateCircleInput 不含 latitude/longitude/address(后端 PUT schema 不允许改位置),
 *    提交时排除这三个字段;若用户未重新选位置,使用原值
 * 2. 圈子创建后 status=pending,管理员审核通过后自动上线
 * 3. 成功 Taro.redirectTo 到圈子详情页(避免返回时回到创建页)
 *
 * 简化:
 * - 活动时间用单个文本输入框,不强制格式(如"每周六上午 9:00-11:00")
 * - 活动地点选点:weapp 用 Taro.chooseLocation;H5 用 H5LocationPicker 地图选点弹层;
 *   仅展示 address 卡片,不展示经纬度
 */
const CreateCirclePage: React.FC = () => {
  const router = useRouter();
  const user = useUserStore((s) => s.user);

  // 编辑模式圈子 ID(无则为新建)
  const editId: string = (router?.params?.id as string) || '';
  const isEdit: boolean = !!editId;
  // 编辑模式 fetch 防重入标志(避免 useDidShow 在 fetch 失败后反复触发)
  const hasFetchedRef = useRef(false);

  // ====== 表单状态 ======
  const [title, setTitle] = useState('');
  const [tagIds, setTagIds] = useState<string[]>([]);
  // 编辑模式预填时缓存的 TagDTO,用于 TagSelector 已选区展示
  const [selectedTags, setSelectedTags] = useState<TagDTO[] | undefined>(undefined);
  const [description, setDescription] = useState('');
  const [address, setAddress] = useState('');
  // 经纬度不在表单中展示,但提交时需要;编辑模式预填从 circle 取,新建模式从 chooseLocation 取
  const [latitude, setLatitude] = useState<number | null>(null);
  const [longitude, setLongitude] = useState<number | null>(null);
  const [contactPhone, setContactPhone] = useState('');
  const [wechat, setWechat] = useState('');
  const [activityTime, setActivityTime] = useState('');
  const [maxMembers, setMaxMembers] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [loading, setLoading] = useState(false);
  // H5 端地图选点弹层显隐
  const [pickerVisible, setPickerVisible] = useState(false);
  // 轮播图片(0-9 张,首张为默认封面,可选)
  const [coverImages, setCoverImages] = useState<string[]>([]);
  const [uploadingCover, setUploadingCover] = useState(false);

  /** 拉取圈子详情用于编辑预填 */
  const fetchForEdit = async (id: string): Promise<void> => {
    setLoading(true);
    try {
      const data = await getCircle(id);
      setTitle(data.title || '');
      setTagIds(data.tags.map((t) => t.id));
      setSelectedTags(data.tags);
      setDescription(data.description || '');
      setAddress(data.address || '');
      setLatitude(data.latitude);
      setLongitude(data.longitude);
      setContactPhone(data.contactPhone || '');
      setWechat(data.wechat || '');
      setActivityTime(data.activityTime || '');
      setMaxMembers(
        data.maxMembers !== null && data.maxMembers !== undefined
          ? String(data.maxMembers)
          : ''
      );
      setCoverImages(data.coverImages || []);
    } catch (e) {
      Taro.showToast({
        title: (e as Error).message || '加载圈子失败',
        icon: 'none',
      });
    } finally {
      setLoading(false);
    }
  };

  // 进入时若是编辑模式,拉取详情预填
  useDidShow(() => {
    // 未登录守卫:与 pages/profile 行为对称
    if (!useUserStore.getState().isLoggedIn) {
      Taro.reLaunch({ url: '/pages/login/index' });
      return;
    }
    // 新建模式:仅 TEACHER 可创建圈子
    if (!isEdit && useUserStore.getState().user?.role !== 'TEACHER') {
      Taro.showToast({ title: '请先完成教师认证', icon: 'none' });
      Taro.navigateTo({ url: '/pages/teacher-certification/index' });
      return;
    }
    // 编辑模式:仅当未拉取过时触发,避免 useDidShow 反复请求
    if (isEdit && !hasFetchedRef.current) {
      hasFetchedRef.current = true;
      void fetchForEdit(editId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  });

  /** 选地点:weapp 用 chooseLocation,H5 打开地图选点弹层 */
  const handleChooseLocation = async (): Promise<void> => {
    try {
      if (process.env.TARO_ENV === 'weapp') {
        const res = await Taro.chooseLocation({});
        setLatitude(res.latitude);
        setLongitude(res.longitude);
        setAddress(res.address || res.name || '已选择位置');
      } else {
        // H5:打开地图选点弹层(拖动选点 + 逆地理编码)
        setPickerVisible(true);
      }
    } catch (e) {
      const err = e as Error & { errMsg?: string };
      // 用户取消静默
      if (err?.errMsg && /cancel/i.test(err.errMsg)) return;
      Taro.showToast({
        title: err?.message || '定位失败,请检查授权',
        icon: 'none',
      });
    }
  };

  /** H5 选点弹层确认回调 */
  const handlePickerConfirm = (loc: {
    latitude: number;
    longitude: number;
    address: string;
  }): void => {
    setLatitude(loc.latitude);
    setLongitude(loc.longitude);
    setAddress(loc.address);
    setPickerVisible(false);
  };

  // ====== 实时校验 ======
  const trimmedTitle = title.trim();
  const trimmedDescription = description.trim();
  const trimmedPhone = contactPhone.trim();
  const trimmedWechat = wechat.trim();
  const trimmedActivityTime = activityTime.trim();

  // 必填项校验
  const titleValid: boolean =
    trimmedTitle.length >= 1 && trimmedTitle.length <= TITLE_MAX;
  const descriptionValid: boolean =
    trimmedDescription.length >= 1 && trimmedDescription.length <= DESCRIPTION_MAX;
  const tagsValid: boolean = tagIds.length >= 1 && tagIds.length <= TAGS_MAX;
  const locationValid: boolean =
    !!address && latitude !== null && longitude !== null;

  // 联系电话与微信号至少填一项
  const hasContact: boolean = trimmedPhone !== '' || trimmedWechat !== '';
  // 手机号格式校验(若填写)
  const phoneValid: boolean = trimmedPhone === '' || PHONE_RE.test(trimmedPhone);

  // 人数上限校验(若填写)
  const maxMembersNum: number | null = maxMembers === '' ? null : Number(maxMembers);
  const maxMembersValid: boolean =
    maxMembers === '' ||
    (!isNaN(maxMembersNum as number) &&
      (maxMembersNum as number) >= MAX_MEMBERS_MIN &&
      (maxMembersNum as number) <= MAX_MEMBERS_MAX);

  // 表单整体可提交
  const canSubmit: boolean =
    titleValid &&
    descriptionValid &&
    tagsValid &&
    locationValid &&
    hasContact &&
    phoneValid &&
    maxMembersValid &&
    !submitting;

  // 错误提示(用于按钮下方展示)
  const contactErr: string = !hasContact ? '请至少填写一种联系方式' : '';
  const phoneErr: string = !phoneValid ? '手机号格式不正确(11 位)' : '';
  const maxMembersErr: string = !maxMembersValid
    ? `人数上限范围 ${MAX_MEMBERS_MIN}-${MAX_MEMBERS_MAX}`
    : '';

  /** 选择轮播图片(仅图片,1-9 张) */
  const handlePickCover = async (): Promise<void> => {
    if (uploadingCover) return;
    const remaining = COVER_IMAGES_MAX - coverImages.length;
    if (remaining <= 0) {
      Taro.showToast({ title: `最多 ${COVER_IMAGES_MAX} 张`, icon: 'none' });
      return;
    }
    try {
      const res = await Taro.chooseMedia({
        count: remaining,
        mediaType: ['image'], // 仅图片
        sourceType: ['album', 'camera'],
        sizeType: ['compressed'],
        maxDuration: 60,
        camera: 'back',
      });
      if (!res.tempFiles?.length) return;
      setUploadingCover(true);
      // 逐个上传,失败则跳过该文件并提示
      const uploaded: string[] = [];
      for (const f of res.tempFiles) {
        try {
          const file: string | File = f.originalFileObj ?? f.tempFilePath;
          const name =
            (f.originalFileObj && f.originalFileObj.name) ||
            f.tempFilePath ||
            `cover-${Date.now()}`;
          const result = await uploadFile({ file, name, purpose: 'generic' });
          uploaded.push(result.url);
        } catch (e) {
          // 单个文件失败不中断,继续上传其余
          console.warn('[create-circle] cover upload failed:', e);
        }
      }
      if (uploaded.length === 0) {
        Taro.showToast({ title: '上传失败,请重试', icon: 'none' });
        return;
      }
      setCoverImages((prev) =>
        [...prev, ...uploaded].slice(0, COVER_IMAGES_MAX)
      );
      Taro.showToast({
        title: `已上传 ${uploaded.length} 张`,
        icon: 'success',
      });
    } catch (e) {
      const err = e as Error & { errMsg?: string };
      // 用户取消选择时 chooseMedia 会 reject,这里静默
      if (err?.errMsg && /cancel/i.test(err.errMsg)) return;
      Taro.showToast({
        title: err?.message || '选择图片失败',
        icon: 'none',
      });
    } finally {
      setUploadingCover(false);
    }
  };

  /** 删除指定轮播图片 */
  const handleRemoveCover = (idx: number): void => {
    setCoverImages((prev) => prev.filter((_, i) => i !== idx));
  };

  /** 提交 */
  const handleSubmit = async (): Promise<void> => {
    if (!canSubmit) return;
    setSubmitting(true);
    try {
      const lat = latitude as number;
      const lng = longitude as number;
      const finalAddress = address || '已定位';
      const finalMaxMembers =
        maxMembers === '' ? undefined : Number(maxMembers);

      if (isEdit) {
        // 编辑模式:UpdateCircleInput 不含 latitude/longitude/address
        const patch: UpdateCircleInput = {
          title: trimmedTitle,
          tagIds,
          description: trimmedDescription,
          contactPhone: trimmedPhone || undefined,
          wechat: trimmedWechat || undefined,
          activityTime: trimmedActivityTime || undefined,
          maxMembers: finalMaxMembers,
          coverImages: coverImages,
        };
        await updateCircle(editId, patch);
        Taro.redirectTo({ url: `/pages/circle/index?id=${editId}` });
      } else {
        // 新建模式
        const res = await createCircle({
          title: trimmedTitle,
          tagIds,
          description: trimmedDescription,
          latitude: lat,
          longitude: lng,
          address: finalAddress,
          contactPhone: trimmedPhone || undefined,
          wechat: trimmedWechat || undefined,
          activityTime: trimmedActivityTime || undefined,
          maxMembers: finalMaxMembers,
          coverImages: coverImages,
        });
        Taro.redirectTo({ url: `/pages/circle/index?id=${res.circleId}` });
      }
    } catch (e) {
      Taro.showToast({
        title: (e as Error).message || '提交失败',
        icon: 'none',
      });
    } finally {
      setSubmitting(false);
    }
  };

  // 已选标签数量提示
  const tagsCountText = `${tagIds.length}/${TAGS_MAX}`;

  // 是否展示"加载中"(编辑模式预填阶段)
  const showLoading = isEdit && loading && !title;

  // 表单底部错误提示(取第一个非空)
  const formErr: string =
    contactErr || phoneErr || maxMembersErr || '';

  // 标题字数提示
  const titleCount = useMemo(
    () => `${title.length}/${TITLE_MAX}`,
    [title.length]
  );
  const descCount = useMemo(
    () => `${description.length}/${DESCRIPTION_MAX}`,
    [description.length]
  );

  // 退出页面前提示(避免编辑中误退出)——简化:不实现

  return (
    <View className={styles.page}>
      {showLoading ? (
        <View className={styles.center}>
          <Text className={styles.muted}>加载中...</Text>
        </View>
      ) : (
        <ScrollView scrollY className={styles.scroll}>
          {/* ====== 1. 标题 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>
                标题 <Text className={styles.required}>*</Text>
              </Text>
              <Text className={styles.count}>{titleCount}</Text>
            </View>
            <Input
              value={title}
              onChange={setTitle}
              placeholder="1-50 字符,如:陈氏太极拳晨练班"
              maxLength={TITLE_MAX}
              className={styles.input}
            />
          </View>

          {/* ====== 2. 标签搜索选择 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>
                兴趣标签 <Text className={styles.required}>*</Text>
              </Text>
              <Text className={styles.count}>{tagsCountText}</Text>
            </View>
            <TagSelector
              selectedIds={tagIds}
              onChange={setTagIds}
              max={TAGS_MAX}
              selectedTags={selectedTags}
            />
          </View>

          {/* ====== 3. 描述 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>
                圈子介绍 <Text className={styles.required}>*</Text>
              </Text>
              <Text className={styles.count}>{descCount}</Text>
            </View>
            <TextArea
              value={description}
              onChange={(v) => setDescription(v)}
              placeholder="1-500 字符,介绍圈子内容、目标人群等"
              maxLength={DESCRIPTION_MAX}
              rows={4}
              className={styles.textarea}
            />
          </View>

          {/* ====== 3.5 轮播图片(可选,0-9 张) ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>轮播图片</Text>
              <Text className={styles.count}>
                {coverImages.length}/{COVER_IMAGES_MAX}
              </Text>
            </View>
            <Text className={styles.coverHint}>
              可上传 0-9 张图片,首张为默认封面,详情页将以轮播展示
            </Text>
            <View className={styles.coverGrid}>
              {coverImages.map((url, idx) => (
                <View key={`${url}-${idx}`} className={styles.coverItem}>
                  <Image
                    src={url}
                    className={styles.coverThumb}
                    mode="aspectFill"
                  />
                  {idx === 0 && (
                    <View className={styles.coverBadge}>
                      <Text className={styles.coverBadgeText}>封面</Text>
                    </View>
                  )}
                  <View
                    className={styles.coverRemove}
                    onClick={() => handleRemoveCover(idx)}
                  >
                    <Text className={styles.coverRemoveIcon}>×</Text>
                  </View>
                </View>
              ))}
              {coverImages.length < COVER_IMAGES_MAX && (
                <View className={styles.coverAdd} onClick={handlePickCover}>
                  <Text className={styles.coverAddIcon}>+</Text>
                  <Text className={styles.coverAddText}>
                    {uploadingCover ? '上传中...' : '添加'}
                  </Text>
                </View>
              )}
            </View>
          </View>

          {/* ====== 4. 活动地点 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>
                活动地点 <Text className={styles.required}>*</Text>
              </Text>
            </View>
            <View className={styles.locationCard} onClick={handleChooseLocation}>
              <Text
                className={
                  address ? styles.locationText : styles.locationPlaceholder
                }
              >
                {address || '点击选择活动地点'}
              </Text>
              <Text className={styles.locationArrow}>选择 ›</Text>
            </View>
          </View>

          {/* ====== 5. 联系电话 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>联系电话</Text>
            </View>
            <Input
              value={contactPhone}
              onChange={setContactPhone}
              placeholder="11 位手机号(与微信号至少填一个)"
              maxLength={11}
              type="number"
              className={styles.input}
            />
          </View>

          {/* ====== 6. 微信号 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>微信号</Text>
            </View>
            <Input
              value={wechat}
              onChange={setWechat}
              placeholder="微信号(与联系电话至少填一个)"
              className={styles.input}
            />
          </View>

          {/* ====== 7. 活动时间 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>活动时间</Text>
            </View>
            <Input
              value={activityTime}
              onChange={setActivityTime}
              placeholder="如:每周六上午 9:00-11:00"
              className={styles.input}
            />
          </View>

          {/* ====== 8. 人数上限 ====== */}
          <View className={styles.field}>
            <View className={styles.fieldHeader}>
              <Text className={styles.label}>人数上限</Text>
            </View>
            <Input
              value={maxMembers}
              onChange={setMaxMembers}
              placeholder={`可选,范围 ${MAX_MEMBERS_MIN}-${MAX_MEMBERS_MAX}`}
              type="number"
              className={styles.input}
            />
          </View>

          {/* 提示:审核说明 */}
          {!isEdit && (
            <Text className={styles.upgradeHint}>
              提交后需管理员审核通过,圈子才能上线
            </Text>
          )}
        </ScrollView>
      )}

      {/* ====== 底部固定提交按钮 ====== */}
      <View className={styles.footer}>
        <Button
          type="primary"
          shape="round"
          block
          size="large"
          loading={submitting}
          disabled={!canSubmit}
          onClick={handleSubmit}
        >
          {isEdit ? '保存修改' : '创建圈子'}
        </Button>
        {formErr && <Text className={styles.footerErr}>{formErr}</Text>}
      </View>

      {/* ====== H5 端地图选点弹层 ====== */}
      {process.env.TARO_ENV === 'h5' && (
        <H5LocationPicker
          visible={pickerVisible}
          initialLat={latitude}
          initialLng={longitude}
          onConfirm={handlePickerConfirm}
          onClose={() => setPickerVisible(false)}
        />
      )}
    </View>
  );
};

export default CreateCirclePage;
