// frontend_uniapp/src/pages/publish/publish.vue
<script lang="ts" setup>
import { computed, ref } from 'vue'
import { useUserStore } from '@/store/user'
import { useLocationStore } from '@/store/location'
import { useMatchStore } from '@/store/match'
import { publishLocation } from '@/api/locations'
import MapView from '@/components/MapView/MapView.vue'
import { reverseGeocode } from '@/utils/amap'
import { getCurrentLocation } from '@/utils/location'

definePage({
  style: {
    navigationBarTitleText: '发布定位',
  },
})

/** 可选匹配范围(公里),与后端 LocationPublishInput.rangeKm 一致 */
const RANGE_OPTIONS: Array<{ label: string; value: 1 | 5 | 10 | 30 }> = [
  { label: '1km', value: 1 },
  { label: '5km', value: 5 },
  { label: '10km', value: 10 },
  { label: '30km', value: 30 },
]

const userStore = useUserStore()
const locationStore = useLocationStore()
const matchStore = useMatchStore()
const user = computed(() => userStore.userInfo)

// 从 location store 预填(若之前已选过位置)
const latitude = ref<number | null>(locationStore.latitude)
const longitude = ref<number | null>(locationStore.longitude)
const address = ref<string | null>(locationStore.address)
const rangeKm = ref<1 | 5 | 10 | 30>(5)
const submitting = ref(false)
const locating = ref(false)
// H5 端地图选点弹层显隐
const pickerVisible = ref(false)
// 发布类型 Tab:location 定位发布 / circle 圈子发布
const publishType = ref<'location' | 'circle'>('location')

/** 切换到"发布圈子":TEACHER 直接跳转,USER 弹窗提示需提交认证材料 */
function handleSwitchToCircle() {
  if (user.value?.role === 'TEACHER') {
    uni.navigateTo({ url: '/pages/create-circle/create-circle' })
    return
  }
  // USER(或其他非 TEACHER 角色):弹窗提示需要提交认证材料
  uni.showModal({
    title: '教师认证',
    content: '创建圈子需要提交教师认证材料(证书照片或视频),管理员审核通过后圈子才能上线。是否继续?',
    confirmText: '去创建',
    success(res) {
      if (res.confirm) {
        uni.navigateTo({ url: '/pages/create-circle/create-circle' })
      }
    },
  })
}

const tagIds = computed(() => (user.value?.tags || []).map(t => t.id))
const hasTags = computed(() => tagIds.value.length > 0)
const hasLocation = computed(() => latitude.value !== null && longitude.value !== null)

// 进入时若无位置,自动尝试一次定位(静默,失败不打扰)
onShow(() => {
  if (latitude.value === null || longitude.value === null) {
    getCurrentLocation()
      .then(async (res) => {
        latitude.value = res.latitude
        longitude.value = res.longitude
        // #ifdef H5
        // H5 端用高德逆地理拿到真实地址;小程序端保持 "已定位" 兜底
        const addr = await reverseGeocode(res.latitude, res.longitude)
        address.value = address.value ?? addr
        // #endif
        // #ifndef H5
        address.value = address.value ?? '已定位'
        // #endif
      })
      .catch((err) => {
        console.warn('[publish] getCurrentLocation failed:', err?.message || err)
      })
  }
})

/**
 * 重新定位/选择位置:
 * - 小程序端:uni.chooseLocation 原生选点(可选点 + 拿地址)
 * - H5:打开 H5LocationPicker 地图选点弹层
 */
async function handleRelocate() {
  if (locating.value) return
  // #ifdef H5
  pickerVisible.value = true
  return
  // #endif
  // #ifndef H5
  locating.value = true
  try {
    // chooseLocation 无 type 参数(仅 getLocation 有),不传默认 gcj02
    const res = await uni.chooseLocation({})
    latitude.value = res.latitude
    longitude.value = res.longitude
    address.value = res.address || res.name || '已选择位置'
  }
  catch (e) {
    const err = e as Error & { errMsg?: string }
    // 用户取消静默
    if (err?.errMsg && /cancel/i.test(err.errMsg)) return
    uni.showToast({ title: err?.message || '定位失败,请检查授权', icon: 'none' })
  }
  finally {
    locating.value = false
  }
  // #endif
}

/** H5 选点弹层确认回调 */
function handlePickerConfirm(loc: { latitude: number; longitude: number; address: string }) {
  latitude.value = loc.latitude
  longitude.value = loc.longitude
  address.value = loc.address
  pickerVisible.value = false
}

/** 跳兴趣选择页 */
function handleEditTags() {
  uni.navigateTo({ url: '/pages/search/search' })
}

/** 发布并匹配 */
async function handlePublish() {
  if (!hasTags.value) {
    uni.showToast({ title: '请先选择兴趣', icon: 'none' })
    return
  }
  if (!hasLocation.value) {
    uni.showToast({ title: '请先选择位置', icon: 'none' })
    return
  }
  if (submitting.value) return
  submitting.value = true
  try {
    const lat = latitude.value as number
    const lng = longitude.value as number
    await publishLocation({
      latitude: lat,
      longitude: lng,
      address: address.value || '已定位',
      tagIds: tagIds.value,
      rangeKm: rangeKm.value,
    })
    // 缓存位置到 location store
    locationStore.setLocation(lat, lng, address.value)
    // 预填 match store(暂不带结果,匹配页进入时拉取)
    matchStore.setMatchResult({
      rangeKm: rangeKm.value,
      location: { latitude: lat, longitude: lng },
      tagIds: tagIds.value,
    })
    uni.navigateTo({ url: '/pages/match/match' })
  }
  catch (e) {
    // 含 429 频控,直接展示后端 message
    uni.showToast({ title: (e as Error).message || '发布失败', icon: 'none' })
  }
  finally {
    submitting.value = false
  }
}

const tagsText = computed(() => {
  return hasTags.value
    ? (user.value?.tags || []).map(t => t.name).join('、')
    : '尚未选择兴趣,点击去选择'
})
</script>

<template>
  <view class="flex min-h-screen flex-col bg-[#f7f8fa] pb-40">
    <!-- ====== 0. 发布类型 Tab ====== -->
    <view class="flex bg-white">
      <view
        class="flex-1 py-3 text-center text-sm"
        :class="publishType === 'location' ? 'font-medium text-[#018d71]' : 'text-[#666]'"
        @click="publishType = 'location'"
      >
        发布定位
      </view>
      <view
        class="flex-1 py-3 text-center text-sm"
        :class="publishType === 'circle' ? 'font-medium text-[#018d71]' : 'text-[#666]'"
        @click="handleSwitchToCircle"
      >
        发布圈子
      </view>
    </view>

    <!-- ====== 1. 顶部地图 ====== -->
    <view class="relative h-56 bg-white">
      <view v-if="hasLocation" class="h-full w-full">
        <MapView
          :latitude="latitude as number"
          :longitude="longitude as number"
          :scale="15"
          show-location
        />
      </view>
      <view v-else class="flex h-full w-full flex-col items-center justify-center bg-[#f5f6f7]">
        <text class="text-sm text-[#999]">
          未获取到位置
        </text>
        <text class="mt-1 text-xs text-[#ccc]">
          点击右下角"选择位置"
        </text>
      </view>
      <view
        class="absolute right-4 bottom-4 rounded-full bg-[#018d71] px-4 py-2"
        @click="handleRelocate"
      >
        <text class="text-xs text-white">
          {{ locating ? '定位中...' : '选择位置' }}
        </text>
      </view>
    </view>

    <!-- ====== 2. 当前位置卡片 ====== -->
    <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
      <text class="block text-sm font-medium text-[#333]">
        当前位置
      </text>
      <text class="mt-1 block text-base text-[#333]">
        {{ hasLocation ? (address || '已定位') : '点击地图选择位置' }}
      </text>
      <text v-if="hasLocation" class="mt-1 block text-xs text-[#999]">
        经纬度:{{ Number(latitude).toFixed(6) }}, {{ Number(longitude).toFixed(6) }}
      </text>
    </view>

    <!-- ====== 3. 我的兴趣卡片 ====== -->
    <view class="mx-4 mt-3 rounded-2xl bg-white p-4" @click="handleEditTags">
      <view class="flex items-center justify-between">
        <text class="text-sm font-medium text-[#333]">
          我的兴趣
        </text>
        <text class="text-sm text-[#018d71]">
          编辑 ›
        </text>
      </view>
      <text class="mt-1 block text-base text-[#333]">
        {{ tagsText }}
      </text>
      <text class="mt-1 block text-xs text-[#999]">
        共 {{ tagIds.length }} 个标签
      </text>
    </view>

    <!-- ====== 4. 范围选择 ====== -->
    <view class="mx-4 mt-3 rounded-2xl bg-white p-4">
      <text class="block text-sm font-medium text-[#333]">
        匹配范围
      </text>
      <view class="mt-3 flex gap-2">
        <view
          v-for="opt in RANGE_OPTIONS"
          :key="opt.value"
          class="flex-1 rounded-lg py-2 text-center"
          :class="rangeKm === opt.value ? 'bg-[#018d71]' : 'bg-[#f5f6f7]'"
          @click="rangeKm = opt.value"
        >
          <text :class="rangeKm === opt.value ? 'text-sm font-medium text-white' : 'text-sm text-[#666]'">
            {{ opt.label }}
          </text>
        </view>
      </view>
    </view>

    <!-- ====== 5. 发布按钮 ====== -->
    <view class="mx-4 mt-4">
      <button
        class="h-12 rounded-full bg-[#018d71] text-base font-medium text-white"
        :loading="submitting"
        :disabled="!hasTags || !hasLocation"
        @click="handlePublish"
      >
        发布并匹配
      </button>
      <text v-if="!hasTags" class="mt-2 block text-center text-xs text-[#999]">
        请先选择兴趣
      </text>
      <text v-else-if="!hasLocation" class="mt-2 block text-center text-xs text-[#999]">
        请先选择位置
      </text>
    </view>

    <!-- ====== H5 端地图选点弹层 ====== -->
    <!-- #ifdef H5 -->
    <H5LocationPicker
      :visible="pickerVisible"
      :initial-lat="latitude"
      :initial-lng="longitude"
      @confirm="handlePickerConfirm"
      @close="pickerVisible = false"
    />
    <!-- #endif -->
  </view>
</template>

<style lang="scss" scoped>
//
</style>

// frontend/src/pages/publish/index.tsx
import React, { useEffect, useState } from 'react';
import { View, Text } from '@tarojs/components';
import { Button } from '@nutui/nutui-react-taro';
import Taro from '@tarojs/taro';
import { useUserStore } from '@/store/user';
import { useLocationStore } from '@/store/location';
import { useMatchStore } from '@/store/match';
import { publishLocation } from '@/services/locations';
import MapView from '@/components/MapView';
import H5LocationPicker from '@/components/H5LocationPicker';
import { reverseGeocode } from '@/utils/amap';
import { getCurrentLocation } from '@/utils/location';
import styles from './index.module.scss';

/** 可选匹配范围(公里),与后端 LocationPublishInput.rangeKm 一致 */
const RANGE_OPTIONS: Array<{ label: string; value: 1 | 5 | 10 | 30 }> = [
  { label: '1km', value: 1 },
  { label: '5km', value: 5 },
  { label: '10km', value: 10 },
  { label: '30km', value: 30 },
];

/**
 * 发布定位页。
 *
 * 流程:
 * 1. 顶部地图展示当前定位;"选择位置"按钮触发 chooseLocation(weapp)/ H5LocationPicker(H5 选点)
 * 2. 当前位置卡片展示地址与经纬度
 * 3. 我的兴趣卡片展示 user.tags,点击跳 pages/search 修改
 * 4. 范围 Tab(1/5/10/30km)
 * 5. "发布并匹配":校验兴趣/位置后调 publishLocation,
 *    成功后缓存 location + 预填 match store,跳 pages/match
 *
 * 平台差异:
 * - weapp:Taro.chooseLocation 直接拿到地址;地图用 Taro 原生 <Map>(腾讯地图)
 * - H5:chooseLocation 不可用,用 H5LocationPicker 弹层让用户拖动地图选点 + 高德逆地理拿真实地址;
 *   顶部展示地图用 MapView(高德 JS API)
 */
const PublishPage: React.FC = () => {
  const user = useUserStore((s) => s.user);
  const setLocationStore = useLocationStore((s) => s.setLocation);
  const setMatchResult = useMatchStore((s) => s.setMatchResult);

  // 从 location store 预填(若之前已选过位置)
  const locStore = useLocationStore();

  const [latitude, setLatitude] = useState<number | null>(locStore.latitude);
  const [longitude, setLongitude] = useState<number | null>(locStore.longitude);
  const [address, setAddress] = useState<string | null>(locStore.address);
  const [rangeKm, setRangeKm] = useState<1 | 5 | 10 | 30>(5);
  const [submitting, setSubmitting] = useState(false);
  const [locating, setLocating] = useState(false);
  // H5 端地图选点弹层显隐
  const [pickerVisible, setPickerVisible] = useState(false);
  // 发布类型 Tab:location 定位发布 / circle 圈子发布
  const [publishType, setPublishType] = useState<'location' | 'circle'>('location');

  /** 切换到"发布圈子":TEACHER 直接跳转,USER 弹窗提示需提交认证材料 */
  const handleSwitchToCircle = (): void => {
    if (user?.role === 'TEACHER') {
      Taro.navigateTo({ url: '/pages/create-circle/index' });
      return;
    }
    // USER(或其他非 TEACHER 角色):弹窗提示需要提交认证材料
    Taro.showModal({
      title: '教师认证',
      content:
        '创建圈子需要提交教师认证材料(证书照片或视频),管理员审核通过后圈子才能上线。是否继续?',
      confirmText: '去创建',
      success: (res) => {
        if (res.confirm) {
          Taro.navigateTo({ url: '/pages/create-circle/index' });
        }
      },
    });
  };

  const tagIds = (user?.tags || []).map((t) => t.id);
  const hasTags = tagIds.length > 0;
  const hasLocation = latitude !== null && longitude !== null;

  // 进入时若无位置,自动尝试一次定位(静默,失败不打扰)
  useEffect(() => {
    if (latitude === null || longitude === null) {
      getCurrentLocation()
        .then(async (res) => {
          setLatitude(res.latitude);
          setLongitude(res.longitude);
          // H5 端用高德逆地理拿到真实地址;weapp 保持 "已定位" 兜底
          if (process.env.TARO_ENV === 'h5') {
            const addr = await reverseGeocode(res.latitude, res.longitude);
            setAddress((prev) => prev ?? addr);
          } else {
            setAddress((prev) => prev ?? '已定位');
          }
        })
        .catch((err) => {
          console.warn('[publish] getCurrentLocation failed:', err?.message || err);
        });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /**
   * 重新定位/选择位置:
   * - weapp:Taro.chooseLocation 原生选点(可选点 + 拿地址)
   * - H5:打开 H5LocationPicker 地图选点弹层,允许用户拖动选择其他地点
   */
  const handleRelocate = async (): Promise<void> => {
    if (locating) return;
    if (process.env.TARO_ENV === 'h5') {
      // H5 端:打开地图选点弹层(拖动选点 + 逆地理编码)
      setPickerVisible(true);
      return;
    }
    // weapp:chooseLocation 选点
    setLocating(true);
    try {
      // chooseLocation 无 type 参数(仅 getLocation 有),不传默认 gcj02
      const res = await Taro.chooseLocation({});
      setLatitude(res.latitude);
      setLongitude(res.longitude);
      setAddress(res.address || res.name || '已选择位置');
    } catch (e) {
      const err = e as Error & { errMsg?: string };
      // 用户取消静默
      if (err?.errMsg && /cancel/i.test(err.errMsg)) return;
      Taro.showToast({
        title: err?.message || '定位失败,请检查授权',
        icon: 'none',
      });
    } finally {
      setLocating(false);
    }
  };

  /** H5 选点弹层确认回调 */
  const handlePickerConfirm = (loc: {
    latitude: number;
    longitude: number;
    address: string;
  }): void => {
    setLatitude(loc.latitude);
    setLongitude(loc.longitude);
    setAddress(loc.address);
    setPickerVisible(false);
  };

  /** 跳兴趣选择页 */
  const handleEditTags = (): void => {
    Taro.navigateTo({ url: '/pages/search/index' });
  };

  /** 发布并匹配 */
  const handlePublish = async (): Promise<void> => {
    if (!hasTags) {
      Taro.showToast({ title: '请先选择兴趣', icon: 'none' });
      return;
    }
    if (!hasLocation) {
      Taro.showToast({ title: '请先选择位置', icon: 'none' });
      return;
    }
    if (submitting) return;
    setSubmitting(true);
    try {
      const lat = latitude as number;
      const lng = longitude as number;
      await publishLocation({
        latitude: lat,
        longitude: lng,
        address: address || '已定位',
        tagIds,
        rangeKm,
      });
      // 缓存位置到 location store
      setLocationStore(lat, lng, address);
      // 预填 match store(暂不带结果,匹配页进入时拉取)
      setMatchResult({
        rangeKm,
        location: { latitude: lat, longitude: lng },
        tagIds,
      });
      Taro.navigateTo({ url: '/pages/match/index' });
    } catch (e) {
      // 含 429 频控,直接展示后端 message
      Taro.showToast({
        title: (e as Error).message || '发布失败',
        icon: 'none',
      });
    } finally {
      setSubmitting(false);
    }
  };

  const tagsText = hasTags
    ? (user?.tags || []).map((t) => t.name).join('、')
    : '尚未选择兴趣,点击去选择';

  return (
    <View className={styles.page}>
      {/* ====== 0. 发布类型 Tab ====== */}
      <View className={styles.typeTabs}>
        <View
          className={`${styles.typeItem} ${publishType === 'location' ? styles.typeItemActive : ''}`}
          onClick={() => setPublishType('location')}
        >
          <Text
            className={publishType === 'location' ? styles.typeItemTextActive : styles.typeItemText}
          >
            发布定位
          </Text>
        </View>
        <View
          className={`${styles.typeItem} ${publishType === 'circle' ? styles.typeItemActive : ''}`}
          onClick={handleSwitchToCircle}
        >
          <Text
            className={publishType === 'circle' ? styles.typeItemTextActive : styles.typeItemText}
          >
            发布圈子
          </Text>
        </View>
      </View>

      {/* ====== 1. 顶部地图 ====== */}
      <View className={styles.mapWrap}>
        {hasLocation ? (
          <MapView
            latitude={latitude as number}
            longitude={longitude as number}
            scale={15}
            showLocation
          />
        ) : (
          <View className={styles.mapPlaceholder}>
            <Text className={styles.mapPlaceholderText}>未获取到位置</Text>
            <Text className={styles.mapPlaceholderHint}>
              点击右下角"选择位置"
            </Text>
          </View>
        )}
        <Button
          type="primary"
          size="small"
          shape="round"
          loading={locating}
          onClick={handleRelocate}
          className={styles.relocateBtn}
        >
          选择位置
        </Button>
      </View>

      {/* ====== 2. 当前位置卡片 ====== */}
      <View className={styles.card}>
        <Text className={styles.cardTitle}>当前位置</Text>
        <Text className={styles.cardValue}>
          {hasLocation
            ? address || '已定位'
            : '点击地图选择位置'}
        </Text>
        {hasLocation && (
          <Text className={styles.cardMeta}>
            经纬度:{latitude?.toFixed(6)}, {longitude?.toFixed(6)}
          </Text>
        )}
      </View>

      {/* ====== 3. 我的兴趣卡片 ====== */}
      <View className={styles.card} onClick={handleEditTags}>
        <View className={styles.cardHeader}>
          <Text className={styles.cardTitle}>我的兴趣</Text>
          <Text className={styles.cardArrow}>编辑 ›</Text>
        </View>
        <Text className={styles.cardValue}>{tagsText}</Text>
        <Text className={styles.cardMeta}>
          共 {tagIds.length} 个标签
        </Text>
      </View>

      {/* ====== 4. 范围选择 ====== */}
      <View className={styles.card}>
        <Text className={styles.cardTitle}>匹配范围</Text>
        <View className={styles.rangeTabs}>
          {RANGE_OPTIONS.map((opt) => {
            const active = rangeKm === opt.value;
            return (
              <View
                key={opt.value}
                className={`${styles.rangeItem} ${active ? styles.rangeItemActive : ''}`}
                onClick={() => setRangeKm(opt.value)}
              >
                <Text
                  className={
                    active ? styles.rangeItemTextActive : styles.rangeItemText
                  }
                >
                  {opt.label}
                </Text>
              </View>
            );
          })}
        </View>
      </View>

      {/* ====== 5. 发布按钮 ====== */}
      <View className={styles.footer}>
        <Button
          type="primary"
          shape="round"
          block
          size="large"
          loading={submitting}
          disabled={!hasTags || !hasLocation}
          onClick={handlePublish}
        >
          发布并匹配
        </Button>
        {!hasTags && (
          <Text className={styles.footerHint}>请先选择兴趣</Text>
        )}
        {hasTags && !hasLocation && (
          <Text className={styles.footerHint}>请先选择位置</Text>
        )}
      </View>

      {/* ====== H5 端地图选点弹层 ====== */}
      {process.env.TARO_ENV === 'h5' && (
        <H5LocationPicker
          visible={pickerVisible}
          initialLat={latitude}
          initialLng={longitude}
          onConfirm={handlePickerConfirm}
          onClose={() => setPickerVisible(false)}
        />
      )}
    </View>
  );
};

export default PublishPage;
